services:
  - type: web
    name: mysql-server
    env: docker
    repo: ianpurifying/SE1project_IRNVault
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: false
